nasa/Open-Source-Catalog

catalog.json

Hi, we're a new NASA open source project.  Hope I got the catalog entry correct.

Adding Trick to catalog.

---

catalog.json

Please see https://software.nasa.gov/software/LEW-19351-1 for more details.

Adding an entry for LEW-19351-1

---

catalog.json

* Updated name to reflect shortening of the name to Open MCT
* Updated description
* Updated contributors
* Added category

Updated Open MCT project details

---

catalog.json

Added PolyCARP and updated the entries for DAIDALUS (WellClear), and Kodiak.

PolyCARP, DAIDALUS, Kodiak

---

catalog.json

@jasonduley please see PR for adding podaacpy to code.nasa.gov.
Thanks 
Lewis

Add podaacpy entry to catalog.json

---

catalog.json

Hi @jasonduley please see trivial updates to Podaacpy entry. Thank you Sir.

Podaacpy update repos location change.

---

catalog.json

Added PRECiSA entry to the catalog

Added PRECiSA entry to the catalog

---

catalog.json

Introduced the TrickFMI software into the catalog.

Update catalog.json file

---

catalog.json

Hi @jasonduley this PR should add the new Sitepod project to the catalog. Thank you.

Add Sitepod project to catalog.json

---

catalog.json

Update catalog.json to add pyCMR info.

---

catalog.json

Modified catalog.json to add information for the Kepler Robovetter code, recently added to https://github.com/nasa/kepler-robovetter

Added entry for kepler-robovetter

---

catalog.json

KeplerPORTs and Kepler-FLTI projects were added to the nasa user github.
Added entries for these two projects into the catalog.json for code.nasa.gov

Updated catalog json for KeplerPORTs and Kepler-FLTI projects

---

catalog.json

Existing catalog entry, just updating data.

Updating dwsolver entry

---

catalog.json

@jasonduley @manilmaskey this accounts for the change is source location for the pyCMR codebase https://github.com/nasa/cmr

Update pyCMR record

---

catalog.json

Please _delete_ the gFTL repository under the nasa org on GitHub.

gFTL has moved to a different location.

---

package-lock.json

"merge": {
"version": "1.2.1",
"resolved": "https://registry.npmjs.org/merge/-/merge-1.2.0.tgz",
"integrity": "sha1-dTHjnUlJwoGma4xabgJl6LBYlNo="

Changed merge for security reasons

---

catalog.json

Hi @jasonduley this adds an entry for our new meta-repository podaac_tools_and_services and removes the duplicate entry for Podaacpy.
It does however retain the `"Labor_Hours": 720` field which was added by someone else previously.

Add entry for podaac_tools_and_services and remove duplicate entry for Podaacpy

---

catalog.json

Hi @evantayloryates please see my accompanying transfer request of IPReS to you personally. Please transfer to NASA Github Org and then merge this when you are satisfied.
Thank you

Add iPReS to Catalog

---

catalog.json

Request to register meta-data for project PX4 Autopilot Simulink Interface.

Added PX4 Autopilot Simulink Interface to Open Source Catalog

---

catalog.json

Adds the 8 new Harmony repositories to the catalog manifest

Add Harmony repositories to catalog
